config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'welcome#index'
   get '/neimenggu' =>'vrapps#neimenggu'
   get '/heart' =>'vrapps#heart'
   get '/split' =>'vrapps#split'
   get '/organicMolecule' =>'vrapps#organicMolecule'
   get '/halloween' =>'vrapps#halloween'
   
   resources :vrapps do
    resources :vrscenes do
      resources :sceneassets
    end
   end

   namespace :api, defaults: {format: 'json'} do
    namespace :v1 do 
      resources :vrapps, only: [:index, :create, :show, :update, :destroy]
    end
  end

end

app/models/sceneasset.rb
class Sceneasset < ActiveRecord::Base
  belongs_to :vrscene
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vrapp.rb
class Vrapp < ActiveRecord::Base
	has_many :vrscenes

	has_attached_file :thumbnail, styles: { large: "1000x1000#", medium: "550x550#" }
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/
end

app/models/vrscene.rb
class Vrscene < ActiveRecord::Base
  belongs_to :vrapp
  has_many :sceneassets

  has_attached_file :scene_img, styles: { large: "8000x4000#", medium: "400x200#" }
  validates_attachment_content_type :scene_img, content_type: /\Aimage\/.*\z/
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
	# disable the CSRF token
  protect_from_forgery with: :null_session

  # disable cookies (no set-cookies header in response)
  before_action :destroy_session

  # disable the CSRF token
  skip_before_action :verify_authenticity_token

  def destroy_session
    request.session_options[:skip] = true
  end
end

app/controllers/api/v1/vrapps_controller.rb
class Api::V1::VrappsController < Api::V1::BaseController

	respond_to :json
	before_action :find_vrapp, only: [:show, :edit, :update, :destroy]

	def show
		respond_with @vrapp
	end

	def index
		respond_with Vrapp.all.order("created_at DESC")
	end

	def new
		@vrapp = Vrapp.new
	end

	def create
		@vrapp =  Vrapp.new vrapp_params
		# @vrapp.name  = params[:name]
		# @vrapp.description = params[:description]

		if @vrapp.save
			render json: @vrapp, status: 201, location: [:api_v1, @vrapp]
		else
			render json: { errors: @vrapp.errors }, status: 422	
		end
	end

private

	def vrapp_params
		# params.require(:vrapp).permit(:name)
		 params.require(:vrapp).permit(:name, :description, :tag, :scenecount, :thumbnail)
	end

	def find_vrapp
		if params[:id].nil?
			
		else
			@vrapp = Vrapp.find(params[:id])
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sceneassets_controller.rb
class SceneassetsController < ApplicationController

	before_action :find_vrapp
	before_action :find_vrscene
	before_action :find_sceneasset, only: [:show, :edit, :update, :destroy]

	def new
		@sceneasset = @vrscene.sceneassets.new
	end

	def create
		@sceneasset = @vrscene.sceneassets.new sceneasset_params
		if @sceneasset.save
			redirect_to vrapp_vrscene_sceneasset_path(@vrapp, @vrscene, @sceneasset)
		else
			render 'new'
		end
	end

	def show
		
	end

	def edit
		
	end

	def update
		if @sceneasset.update sceneasset_params
			redirect_to vrapp_vrscene_sceneasset_path(@vrapp, @vrscene, @sceneasset), notice: "Successfully saved!"
		else
			render 'edit'
		end
	end

	def destroy
		@sceneasset.destroy
		redirect_to vrapp_vrscene_path(@vrapp, @vrscene)
	end
	private

	def sceneasset_params
		params.require(:sceneasset).permit(:assetname, :location, :text)
	end

	def find_vrapp
		@vrapp = Vrapp.find(params[:vrapp_id])
	end
	def find_vrscene
		@vrscene = Vrscene.find(params[:vrscene_id])
	end
	def find_sceneasset
		@sceneasset = Sceneasset.find(params[:id])
	end
end

app/controllers/vrapps_controller.rb
class VrappsController < ApplicationController

	before_action :find_vrapp, only: [:show, :edit, :update, :destroy]
	before_action :find_vrscene, only: [:show]

	def index
		@vrapps = Vrapp.all.order("created_at DESC")
	end

	def new
		@vrapp = Vrapp.new
	end

	def create
		@vrapp =  Vrapp.new vrapp_params
		if @vrapp.save
			redirect_to @vrapp, notice: "Successfully saved!"
		else
			render 'new', notice: "Unable to save your App!"
		end
	end

	def show
		
	end

	def edit
		
	end

	def update
		if @vrapp.update vrapp_params
			redirect_to @vrapp, notice: "Successfully saved!"
		else
			render 'edit'
		end
	end

	def destroy
		@vrapp.destroy
		redirect_to vrapps_path
	end

private

	def vrapp_params
		params.require(:vrapp).permit(:name, :description, :tag, :scenecount, :thumbnail)
	end
	def find_vrscene
		@vrscenes = Vrscene.where(vrapp_id: @vrapp).order("created_at DESC")
	end
	def find_vrapp
		if params[:id].nil?
			
		else
			@vrapp = Vrapp.find(params[:id])
		end
	end

end

app/controllers/vrscenes_controller.rb
class VrscenesController < ApplicationController

	before_action :find_vrapp
	before_action :find_vrscene, only: [:show, :edit, :update, :destroy]

	def new
		@vrscene = @vrapp.vrscenes.new
		
	end
	def create
		@vrscene = @vrapp.vrscenes.new vrscene_params
		if @vrscene.save
			redirect_to vrapp_vrscene_path(@vrapp, @vrscene)
		else
			render 'new'
		end
	end

	def show
		@sceneassets = Sceneasset.where(vrscene_id: @vrscene).order("created_at DESC")
	end

	def edit
		
	end

	def update
		if @vrscene.update vrscene_params
			redirect_to vrapp_vrscene_path(@vrapp, @vrscene), notice: "Successfully saved!"
		else
			render 'edit'
		end
	end
	def destroy
		@vrscene.destroy
		redirect_to vrapp_path(@vrapp)
	end

	private

	def vrscene_params
		params.require(:vrscene).permit(:scenename, :orderid, :scenetype, :scene_img)
	end

	def find_vrapp
		@vrapp = Vrapp.find(params[:vrapp_id])
	end
	def find_vrscene
		@vrscene = Vrscene.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end
	def neimenggu
		
	end
	def heart
		
	end

	def split
		
	end
end

app/helpers/api/v1/base_helper.rb
module Api::V1::BaseHelper
end

app/helpers/api/v1/vrapps_helper.rb
module Api::V1::VrappsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sceneassets_helper.rb
module SceneassetsHelper
end

app/helpers/vrapps_helper.rb
module VrappsHelper
end

app/helpers/vrscenes_helper.rb
module VrscenesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SRT VR</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
	<link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sceneassets/_form.html.erb
<%= form_for ([@vrapp, @vrscene, @sceneasset]) do |f|%>
	<%= f.label :assetname %><br>
	<%= f.text_field :assetname %>

	<br>
	<br>

	<%= f.label :location %><br>
	<%= f.text_field :location %>

	<br>
	<br>

	<%= f.label :text %><br>
	<%= f.text_field :text %>

	<br>
	<br>

	<%= f.submit %>

<% end %>

app/views/sceneassets/edit.html.erb
<div id="form">
  <div class="wrapper_skinny">
		<h1>Edit Asset</h1>
		<%= render 'form' %>

	</div>
</div>

app/views/sceneassets/new.html.erb
<div id="form">
  <div class="wrapper_skinny">
		<h1>New Asset</h1>
		<%= render 'form' %>

	</div>
</div>

app/views/sceneassets/show.html.erb
	<div id="vrapp_show">

		
			<div id="breadcrumb">
					<%= link_to vrapps_path do %>
						All App
						<span>/</span>
						<%= link_to @vrapp.name, vrapp_path(@vrapp) %>
						<span>/</span>
						<%= link_to @vrscene.scenename, vrapp_vrscene_path(@vrapp, @vrscene) %>
						<span>/</span>
						<%= link_to @sceneasset.assetname, vrapp_vrscene_sceneasset_path(@vrapp, @vrscene, @sceneasset) %>
					<% end %>
			</div>
		
		 <div id="episode_content">
		 	<div class="wrapper_skinny">
		 			<img src="images/podcast1.jpg" alt="" class="current_episode_thumbnail">
		 			<h2><%= @sceneasset.assetname %></h2>
						<p class="description">
							Location: <%= @sceneasset.location %>
						</p>
						<p class="description">
							text: <%= @sceneasset.text %>
						</p>
						<p class="description">
							<%= link_to "Edit", edit_vrapp_vrscene_sceneasset_path(@vrapp, @vrscene, @sceneasset) %>
							<%= link_to "Delete", vrapp_vrscene_sceneasset_path(@vrapp, @vrscene, @sceneasset), method: :delete, data: {confirm: "Are your sure?"} %>
						</p>
		 	</div>
		 </div>
		
	</div>

app/views/vrapps/_form.html.erb
<%= form_for @vrapp do |f| %>
	<% if @vrapp.errors.any? %>
		<h3><%= pluralize(@vrapp.errors.count, "error") %> prevented this App from saving:</h3>
		<ul>
			<% @vrapp.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :name %><br>
	<%= f.text_field :name %>

	<br>
	<br>

  <%= f.label :description %><br>
	<%= f.text_area :description %>

	<br>
	<br>

	<%= f.label :tag %><br>
	<%= f.text_field :tag %>

	<br>
	<br>

	<%= f.label :thumbnail %><br>
	<%= f.file_field :thumbnail %>

	<br>
	<br>

	<%= f.submit "Save", class: "button button_highlight button_block" %>
<% end %>

app/views/vrapps/edit.html.erb
<div id="form">
  <div class="wrapper_skinny">

		<%= render 'form' %>

	</div>
</div>

app/views/vrapps/halloween.html.erb
<script src="/halloween/krpano.js"></script>

<div id="pano" style="width:100%;height:100%;">
	<noscript><table style="width:100%;height:100%;"><tr style="vertical-align:middle;text-align:center;"><td>ERROR:<br><br>Javascript not activated<br><br></td></tr></table></noscript>
	<script>
		embedpano({swf:"videoplayer.swf", xml:"halloween/halloween.xml", target:"pano", html5:"auto", mobilescale:1.0, passQueryParameters:true});
	</script>
</div>

app/views/vrapps/heart.html.erb
<script src="/heart/krpano.js"></script>

<div id="pano" style="width:100%;height:100%;">
	<noscript><table style="width:100%;height:100%;"><tr style="vertical-align:middle;text-align:center;"><td>ERROR:<br><br>Javascript not activated<br><br></td></tr></table></noscript>
	<script>
		embedpano({swf:"videoplayer.swf", xml:"heart/heart.xml", target:"pano", html5:"auto", mobilescale:1.0, passQueryParameters:true});
	</script>
</div>

app/views/vrapps/index.html.erb
<div id="banner" class="vrapps_banner">
		<h1>Discover your favorite VR App</h1>
</div>
	
<div id="vrapps" class="cf">
	<div class="wrapper">
		<ul>
			<% @vrapps.each do |vrapp| %>
					<%= link_to vrapp do %>
					<li>
					<%= image_tag vrapp.thumbnail.url(:medium) %>
						<div class="vrapp_overview">
							<h2><%= vrapp.name %></h2>
							<p class="vrapp_tag"><%= vrapp.tag %></p>
						</div>
					</li>
			  <% end %>
			<% end %>
		</ul>
</div>
		
	</div>

app/views/vrapps/neimenggu.html.erb
<script src="neimenggu/tour.js"></script>

<div id="pano" >
	<noscript><table style="width:100%;height:100%;"><tr style="vertical-align:middle;"><td><div style="text-align:center;">ERROR:<br/><br/>Javascript not activated<br/><br/></div></td></tr></table></noscript>
	<script>
		embedpano({swf:"neimenggu/tour.swf", xml:"neimenggu/tour.xml", target:"pano", html5:"prefer", mobilescale:1.0, passQueryParameters:true});
	</script>

</div>

app/views/vrapps/new.html.erb
<!-- <div id="banner" class="sign_up_banner">
  <h1>Creat your own VR App</h1>
</div> -->
<div id="form">
  <div class="wrapper_skinny">

		<%= render 'form' %>

	</div>
</div>

app/views/vrapps/organicMolecule.html.erb
<script src="/organicMolecule/krpano.js"></script>

<div id="pano" style="width:100%;height:100%;">
	<noscript><table style="width:100%;height:100%;"><tr style="vertical-align:middle;text-align:center;"><td>ERROR:<br><br>Javascript not activated<br><br></td></tr></table></noscript>
	<script>
		embedpano({swf:"videoplayer.swf", xml:"organicMolecule/organicMolecule.xml", target:"pano", html5:"auto", mobilescale:1.0, passQueryParameters:true});
	</script>
</div>

app/views/vrapps/show.html.erb
	<div id="vrapp_show">
		<div id="show_banner">
			<div class="wrapper_skinny">
				<h1><%= @vrapp.name %></h1>
				<p class="description"><%= @vrapp.description %></p>
				<%= link_to "Edit APP", edit_vrapp_path(@vrapp), class: "subscribe_link" %>
				<%= link_to "Delete Scene", vrapp_path(@vrapp), method: :delete, data: {confirm: "Are your sure?"} , class: "subscribe_link"%>
				<%= link_to "New Scene", new_vrapp_vrscene_path(@vrapp), class: "subscribe_link" %>
			</div>
		</div>
		
		<div id="breadcrumb">
				<%= link_to vrapps_path do %>
					All App
					<span>/</span>
					<%= @vrapp.name %>
				<% end %>
		</div>
		
		<div id="episodes">
			<div class="wrapper_skinny">
				<ul class="cf">
					<% @vrscenes.each do |vrscene| %>
							<li class="cf">
								<div class="episode_thumbnail">
									<a href="#">
										<%= image_tag vrscene.scene_img.url(:medium) %>
									</a>
								</div>
								<div class="episode_overview">
									<h2><%= link_to vrscene.scenename, vrapp_vrscene_path(@vrapp, vrscene) %></h2>
									<p class="description">
										Scene Order: <%= vrscene.orderid %> <span>  | </span> Scene Type: <%= vrscene.scenetype %>
									</p>

								</div>
							</li>
					<% end %>
				</ul>
			</div>
		</div>

</div>
	<div class="pagination">
		<span class="previous_page disabled">Previous</span>
		<em class="current">1</em>
		<a href="#">2</a>
		<a href="#" class="next_page">Next</a>

</div>

app/views/vrapps/split.html.erb
<script src="/split/krpano.js"></script>

<div id="pano" style="width:100%;height:100%;">
	<noscript><table style="width:100%;height:100%;"><tr style="vertical-align:middle;text-align:center;"><td>ERROR:<br><br>Javascript not activated<br><br></td></tr></table></noscript>
	<script>
		embedpano({swf:"videoplayer.swf", xml:"split/split.xml", target:"pano", html5:"auto", mobilescale:1.0, passQueryParameters:true});
	</script>
</div>

app/views/vrscenes/_form.html.erb
<%= form_for ([@vrapp, @vrscene]) do |f|%>
	<%= f.label :scenename %><br>
	<%= f.text_field :scenename %>

	<br>
	<br>

	<%= f.label :orderid %><br>
	<%= f.text_field :orderid %>

	<br>
	<br>

	<%= f.label :scenetype %><br>
	<%= f.text_field :scenetype %>

	<br>
	<br>

	<%= f.label :scene_img %><br>
	<%= f.file_field :scene_img %>

	<br>
	<br>

	<%= f.submit %>

<% end %>

app/views/vrscenes/edit.html.erb
<div id="form">
  <div class="wrapper_skinny">
		<h1>Edit Scene</h1>
		<%= render 'form' %>

	</div>
</div>

app/views/vrscenes/new.html.erb
<div id="form">
  <div class="wrapper_skinny">
		<h1>New Scene</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/vrscenes/show.html.erb
	<div id="vrapp_show">
		<div id="show_banner">
		<div class="wrapper_skinny">
			<h1><%= @vrscene.scenename %></h1>
			<p class="description">Scene Order: <%= @vrscene.orderid %> <span>  | </span> Scene Type: <%= @vrscene.scenetype %></p>
				<%= link_to "Edit Scene", edit_vrapp_vrscene_path(@vrapp, @vrscene), class: "subscribe_link" %>
				<%= link_to "Delete Scene", vrapp_vrscene_path(@vrapp, @vrscene), method: :delete, data: {confirm: "Are your sure?"} , class: "subscribe_link"%>
				<%= link_to "New Asset", new_vrapp_vrscene_sceneasset_path(@vrapp, @vrscene), class: "subscribe_link" %>
		</div>

		</div>
		
			<div id="breadcrumb">
					<%= link_to vrapps_path do %>
						All App
						<span>/</span>
						<%= link_to @vrapp.name, vrapp_path(@vrapp) %>
						<span>/</span>
						<%= link_to @vrscene.scenename, vrapp_vrscene_path(@vrapp, @vrscene) %>
					<% end %>
			</div>
		
		 <div id="episodes">
			<div class="wrapper_skinny">
				<ul class="cf">
					<% @sceneassets.each do |sceneasset| %>
							<li class="cf">
								<div class="episode_thumbnail">
									<a href="#">
										<img src="images/podcast1.jpg" alt="">
									</a>
								</div>
								<div class="episode_overview">
									<h2><%= link_to sceneasset.assetname, vrapp_vrscene_sceneasset_path(@vrapp, @vrscene, sceneasset) %></h2>
									<p class="description">
										Location: <%= sceneasset.location %>
									</p>
									<p class="description">
									text: <%= sceneasset.text %>
									</p>
		
								</div>
							</li>
					<% end %>
				</ul>
			</div>
		</div>
		
	</div>
	<div class="pagination">
		<span class="previous_page disabled">Previous</span>
		<em class="current">1</em>
		<a href="#">2</a>
		<a href="#" class="next_page">Next</a>

	</div>

app/views/welcome/index.html.erb
<div id="jumbotron">
<header id = "main_header" class="cf">
	<div class="wrapper">
		<%= image_tag "vrlogo_white.png", id: "logo" %>
		<nav>
			<ul>		
				<li><%= link_to "学科系列", vrapps_path %></li>
				<li><%= link_to "全景课堂", new_vrapp_path %></li>
				<li><%= link_to "联盟介绍", destroy_user_session_path, method: :delete %></li>
				<li><%= link_to "联系我们", new_vrapp_path %></li>
			</ul>
		</nav>
	</div>

</header>
 <div>
  	<%= video_tag "main-show-video.mp4",type: "video/mp4", :controls => false, :autobuffer => true, :autoplay => true, :loop => true, :id => "home-video" %>
  </div>
</div>
<!-- 内容 -->
<div class="content cf">
	<div class="wrapper">
	<div class="logo_content">
		<%= image_tag "vrlogo_black.png", class: "logo_black" %>
	</div>
		
	<h4>最新内容</h4>

	<ul>
			<%= link_to heart_path do %>
				<li>
				<%= image_tag "content_1.jpg" %>

					<div class="content_overview">
						<h2>心脏结构-四中生物课</h2>
						<p class="content_tag">初中/生物</p>
					</div>
				</li>
			<% end %>

			<%= link_to split_path do %>
				<li>
					<%= image_tag "content_2.jpg" %>
					<div class="content_overview">
						<h2>有丝分裂-人大附中生物课</h2>
						<p class="content_tag">高中/生物</p>
					</div>
				</li>
			</a>
			<% end %>

			<%= link_to organicMolecule_path do %>
				<li>
					<%= image_tag "content_3.jpg" %>
					<div class="content_overview">
						<h2>有机分子结构化学鉴定</h2>
						<p class="content_tag">初中/化学</p>
					</div>
				</li>
			</a>
			<% end %>
			<%= link_to halloween_path do %>
				<li>
					<%= image_tag "content_4.jpg" %>
					<div class="content_overview">
						<h2>芳草地国际学校万圣节</h2>
						<p class="content_tag">小学/校园活动</p>
					</div>
				</li>
			</a>
			<% end %>
			<%= link_to neimenggu_path do %>
				<li>
					<%= image_tag "content_5.jpg" %>
					<div class="content_overview">
						<h2>内蒙古草原全景</h2>
						<p class="content_tag">初中/地理</p>
					</div>
				</li>
			<%end %>
			
			<a href="#">
				<li>
					<%= image_tag "content_6.jpg" %>
					<div class="content_overview">
						<h2>火山喷发</h2>
						<p class="content_tag">初中/地理</p>
					</div>
				</li>
			</a>
	</ul>
		</div>
</div>
<!-- 联盟介绍 -->
<div class="supporting">
<div class="wrapper">
	<h4>中国VR教学联盟</h4>
	<p>中国VR教学联盟由教育部基础教育课程教材发展中心指导下的中国教研网<br>
(北京尚睿通教育科技股份有限公司)和一批国内顶尖的中小学、教研机构共同发起。<br><br>
致力于探索和解决VR技术真正应用于中小学课堂教学的具体问题，
促进学生学科核心概念理解、核心方法建立以及学科核心素养的提升。<br>
同时，对于广大中小学教师的教育技术观念和应用能力起到有效地促进。</p>
<%= link_to "了解更多 ->", new_vrapp_path %>
</div>

</div>
<!-- footer -->
<div class="footer cf">
<div class="wrapper_skinny">
	<ul class="cf">
		
		<a href="http://www.teacherclub.com.cn/" target="_Blank">
		<li>
			<h5>中国教师研修网</h5>
			<p>中国教师研修网由全国教师教育学会主办
是一家为全国中小幼教师和教育管理者的专业发展提供
全方位学习服务的专业机构</p>
			</li>
		</a>

		<a href="http://www.zgjiaoyan.com/" target="_Blank">
		<li>
			<h5>中国教研网</h5>
			<p>中国教研网是由教育部基础教育课程教材发展中心指导
各级教研部门支持，中国教师研修网具体负责运营的首个
服务全国教研工作和广大中小学教师专业发展的专业网络平台</p>
		</li>
		</a>

		<a href="http://www.shangruitong.com/" target="_Blank">
		<li>
			<h5>尚睿通教育</h5>
			<p>尚睿通教育科技股份有限公司（简称“尚睿通教育”）
成立于2005年，2016年成功挂牌新三板 （股票代码：835971）
是一家面向中国基础教育领域提供网络服务的高新技术企业</p>
		</li>
		</a>
	</ul>
	<p>尚睿通公司版权所有 京ICP证060239号 电信与信息服务业务许可证 客户服务热线：（010）82235796-846 举报邮箱：sc@yanxiu.com</p>

</div>
</div>